@baseUrl = http://103.127.133.201:3003
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4MzI0NWE5LTE3NzEtNGU4MS05ODAxLTA1MmU1MjMyMGFiZSIsInVzZXJuYW1lIjoicmlmYWkiLCJpYXQiOjE3NjI2NjUwMzgsImV4cCI6MTc2Mjc1MTQzOH0.k7tSzmJmnasWP0MQjASHHSW6049ynT4fSEm_NPM4EBc
@driverID=60a38562-2a9b-4fe9-ae78-badc6be410f5
@vehicleID=1983350b-8844-4ce1-ac7a-d4fe417dc80e
@chassisID=1359ed55-b3e1-4f3a-bd78-7f68472514b4
@equipementID=7198ea19-32f1-4fd1-b961-98560c9faca5
@sparepartID1=f7fc9120-9289-42ed-bf3b-ff59f1c0cb79
@sparepartID2=800f38ae-511b-4c8b-bcfa-ab05e0d5f171
@assetID=8a2dcf01-96ff-41c0-92d1-aabe3cfa4255
@maintenenceID=00118981-31fb-42b6-a031-cabf9485eea3


### Register User
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "fullname": "Ahmad Rifai",
  "username": "rifai",
  "password": "rahasia",
  "role": "ADMIN"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "rifai",
  "password": "rahasia"
}

### Current User / Me
GET  {{baseUrl}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}

### Create Driver
POST  {{baseUrl}}/api/drivers
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "driver_number": "1234568",
  "name": "Ozi Asolole",
  "phone": "085155380996",
  "notes": ""
}

### Get All Drivers
GET {{baseUrl}}/api/drivers
Content-Type: application/json
Authorization: Bearer {{token}}


### Get By ID
GET {{baseUrl}}/api/drivers/{{driverID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Update By ID
PATCH {{baseUrl}}/api/drivers/{{driverID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "driver_number": "1234568",
  "name": "Ozi Asolole Edit",
  "phone": "085155380996",
  "notes": "catatan sejarah",
  "is_active": true
}

### Delete Driver
DELETE {{baseUrl}}/api/drivers/{{driverID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Create Vehicle
POST {{baseUrl}}/api/vehicles
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  // asset
  "asset_code": "1235",
  "name": "Mobil Eropa",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxx",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // vehicle
  "license_plate": "AA 5504 ABC",
  "vehicle_type": "tipeku",
  "color": "merah",
  "year": 2000,
  "engine_number": "xxx",
  "frame_number": "xxx",
  "no_kir": "xxx",
  "kir_due_date": "2021-06-12",
  "stnk_due_date": "2021-06-12",
  "notes": "" 
}

### Get All Vehicle
GET {{baseUrl}}/api/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Vehicle By ID
GET {{baseUrl}}/api/vehicles/{{vehicleID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Update Vehicle
PATCH  {{baseUrl}}/api/vehicles/{{vehicleID}}
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  // asset
  "asset_code": "12354",
  "name": "Mobil Eropa Edit Sekali",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxx",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // vehicle
  "license_plate": "AA 5504 ABC",
  "vehicle_type": "tipeku",
  "color": "merah",
  "year": 2000,
  "engine_number": "xxx",
  "frame_number": "xxx",
  "no_kir": "xxx",
  "kir_due_date": "2021-06-12",
  "stnk_due_date": "2021-06-12",
  "notes": "" 
}

### Delete Vehicle
DELETE {{baseUrl}}/api/vehicles/{{vehicleID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Create Chassis 
POST  {{baseUrl}}/api/chassises
Content-Type: application/json
Authorization: Bearer {{token}}

{
  // asset
  "asset_code": "12354",
  "name": "Mobil Eropa Edit Sekali",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxx",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // chassis
  "chassis_number": "124",
  "chassis_category": "20 feat",
  "chassis_type": "RANGKA",
  "axle_count": 1,
  "no_kir": "124590",
  "kir_due_date": "2021-06-12",
  "notes": "notes"
}

### Get All Chassis
GET {{baseUrl}}/api/chassises
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Chasis By ID
GET {{baseUrl}}/api/chassises/{{chassisID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Update Chassis 
PATCH {{baseUrl}}/api/chassises/{{chassisID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  // asset
  "asset_code": "12354",
  "name": "Mobil Eropa Yak gaesd",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxxd",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // chassis
  "chassis_number": "124",
  "chassis_category": "20 feat",
  "chassis_type": "RANGKA",
  "axle_count": 13,
  "no_kir": "124590",
  "kir_due_date": "2021-06-12",
  "notes": "noto boto sedoyo"
}

### Delete Chassis
DELETE {{baseUrl}}/api/chassises/{{chassisID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Get All Equipment 
GET {{baseUrl}}/api/equipments
Content-Type: application/json
Authorization: Bearer {{token}}

### Create Equipment 
POST {{baseUrl}}/api/equipments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  // asset
  "asset_code": "12354",
  "name": "Mobil Eropa Yak gaesd",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxxd",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // equipment
  "equipment_code": "123",
  "equipment_type": "apa",
  "specification": "spek",
  "condition": "bagus"
}

### Get Equipment By Id
GET {{baseUrl}}/api/equipments/{{equipementID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Equipment By Id
PATCH {{baseUrl}}/api/equipments/{{equipementID}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
  // asset
  "asset_code": "12354",
  "name": "Mobil Eropa Yak gaesd",
  "brand": "Yamasa",
  "model": "modal",
  "serial_number": "xxxdd",
  "purchase_date": "2021-06-12",
  "purchase_price": 1000000,

  // equipment
  "equipment_code": "1233",
  "equipment_type": "apa edit",
  "specification": "spek",
  "condition": "bagus"
}

### Delete Equipement
DELETE {{baseUrl}}/api/equipments/{{equipementID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Create Sparepart
POST {{baseUrl}}/api/spareparts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "SPR-033",
  "name": "Apa",
  "unit": "pcs",
  "price":2000000,
  "stock_quantity":10,
  "description": "no desc"
}


### Get All Sparepart
GET {{baseUrl}}/api/spareparts
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Sparepart By Id
GET {{baseUrl}}/api/spareparts/{{sparepartID1}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Update Sparepart
PATCH {{baseUrl}}/api/spareparts/{{sparepartID1}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "SPR-01",
  "name": "Apa Edit",
  "unit": "pcs",
  "price":2000000,
  "stock_quantity":10,
  "description": "no desc"
}

### Deleta Sparepart
DELETE {{baseUrl}}/api/spareparts/{{sparepartID1}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Create Maintenence
POST {{baseUrl}}/api/maintenences
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "asset_id": "{{assetID}}",
  "driver_id": "{{driverID}}",
  "asset_image_url": "https://localhost:3000",
  "repair_image_urls": ["https://localhost:3000","https://localhost:3000","https://localhost:3000"],
  "km_asset": 1000,
  "spareparts": [
    {"id":"{{sparepartID1}}", "quantity": 1},
    {"id":"{{sparepartID2}}", "quantity": 2}
  ],
  "complaint": "complaint saja",
  "repair_plan": "repair saja"
}

### Get All Maintenence
GET {{baseUrl}}/api/maintenences?size=5&page=3
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Current Maintenence
GET {{baseUrl}}/api/maintenences/me
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Maintenence By Id
GET {{baseUrl}}/api/maintenences/{{maintenenceID}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Upload File
POST {{baseUrl}}/api/upload
Content-Type: multipart/form-data

--WebAppBoundary
Content-Disposition: form-data; name="file"; file="sample.jpg"
Content-Type: image/jpeg

< ./sample.jpg
--WebAppBoundary--
